name: Cache Workflow

on:
  push:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create cache folder
        run: mkdir -p cache-folder

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: cache-folder
          key: cache-252336a

      - name: prime-cache-252336a
        run: echo Cache hit? ${{ steps.cache-step.outputs.cache-hit }}
